import Foundation
import PackageFileSupport
import Testing

/// Holds the pins of the in-family ACP packages equal in the three
/// `Package.resolved` files (update.md §7 item 3).
///
/// The root package, the benchmark package and the demo Xcode project each
/// resolve their dependencies. When one file pins another revision, the demo
/// app or the benchmarks build against another ACP API than the kit. Each pin
/// move changes the files together, and this suite fails for a file that the
/// move did not change.
///
/// The demo project is git-ignored. `Examples/Scripts/xcodeproj_generator.rb`
/// makes it again and copies the root `Package.resolved` into it. Thus a clean
/// checkout has no demo pin file: the suite reads that file only when the
/// generated project exists, and it always checks the copy step of the
/// generator.
@Suite struct ResolvedPinsTests {
  /// The two committed `Package.resolved` files, relative to the package root.
  static let committedPaths = ["Package.resolved", "Benchmarks/Package.resolved"]

  /// The `Package.resolved` file of the generated demo project, relative to
  /// the package root.
  static let demoPath =
    "Examples/AgentViewKitDemo/AgentViewKitDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

  /// The script that makes the Xcode project of each example.
  static let generatorPath = "Examples/Scripts/xcodeproj_generator.rb"

  /// The branch that the manifests follow for each in-family package.
  static let followedBranch = "main"

  /// The revision of each in-family ACP package, keyed by identity.
  ///
  /// FoundationModelsACP `fe0d82d` is `schema-v2.0.0-alpha.7` with
  /// `subscribe(to:)` in place of the removed stream API (`27419fa` and
  /// later). FoundationModelsACPClient `be7e615` has `ConnectionModel` and
  /// `SessionModel` (`a65af8a` and later).
  static let expectedRevisions = [
    "foundationmodelsacp": "fe0d82da1ef488b82d06afb0fd0ee9cd5a31cb98",
    "foundationmodelsacpclient": "be7e615b1db2dc59e48d43bce4276886160ff0f4",
  ]

  /// Tells whether the demo project was generated in this checkout.
  static var demoProjectIsGenerated: Bool {
    guard let url = try? PackageFiles.file(demoPath) else { return false }
    return FileManager.default.fileExists(atPath: url.path(percentEncoded: false))
  }

  /// Reads the in-family ACP pins of one `Package.resolved` file, in identity
  /// order.
  ///
  /// - Parameter path: The path of the file, relative to the package root.
  /// - Returns: The pins of the ACP packages.
  private func acpPins(of path: String) throws -> [ResolvedFile.Pin] {
    let data = try Data(contentsOf: PackageFiles.file(path))
    return try JSONDecoder().decode(ResolvedFile.self, from: data).pins
      .filter { Self.expectedRevisions.keys.contains($0.identity) }
      .sorted { $0.identity < $1.identity }
  }

  @Test(arguments: committedPaths)
  func eachCommittedFilePinsTheExpectedACPRevisions(path: String) throws {
    let pins = try acpPins(of: path)

    #expect(pins.map(\.identity) == Self.expectedRevisions.keys.sorted())
    for pin in pins {
      #expect(pin.state.revision == Self.expectedRevisions[pin.identity], "\(path): \(pin.identity)")
      #expect(pin.state.branch == Self.followedBranch, "\(path): \(pin.identity)")
    }
  }

  @Test(.enabled(if: demoProjectIsGenerated, "The demo project is generated by Scripts/test-examples.sh."))
  func theGeneratedDemoProjectPinsTheRootACPRevisions() throws {
    let root = try acpPins(of: Self.committedPaths[0])

    #expect(try acpPins(of: Self.demoPath) == root)
  }

  @Test func theGeneratorCopiesTheRootPinsIntoTheDemoProject() throws {
    let generator = try PackageFiles.text(of: Self.generatorPath)
    let projectRelativePath = try #require(
      Self.demoPath.firstMatch(of: /\.xcodeproj\/(?<inner>.+)$/)?.output.inner)

    #expect(generator.contains("PROJECT_PINS_PATH = '\(projectRelativePath)'"))
    #expect(generator.contains("File.join(PACKAGE_RELATIVE_PATH, 'Package.resolved')"))
    #expect(generator.contains("FileUtils.cp(pins, destination)"))
  }
}
