import Foundation
import PackageFileSupport
import Testing

/// Holds the pins of the in-family ACP packages equal in the two
/// `Package.resolved` files (`Docs/decisions/dependencies.md`).
///
/// The root package and the demo Xcode project each resolve their
/// dependencies. When the demo file pins another revision, the demo app
/// builds against another ACP API than the kit.
///
/// `Package.resolved` is git-ignored. SwiftPM writes the root file when it
/// resolves the package. The demo project is git-ignored too.
/// `Examples/Scripts/xcodeproj_generator.rb` makes it again and copies the root
/// `Package.resolved` into it. Thus a clean checkout has no demo pin file: the
/// suite reads that file only when the generated project exists, and it always
/// checks the copy step of the generator.
@Suite struct ResolvedPinsTests {
  /// The `Package.resolved` file that SwiftPM writes for the root package,
  /// relative to the package root.
  static let rootPath = "Package.resolved"

  /// The `Package.resolved` file of the generated demo project, relative to
  /// the package root.
  static let demoPath =
    "Examples/AgentViewKitDemo/AgentViewKitDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

  /// The script that makes the Xcode project of each example.
  static let generatorPath = "Examples/Scripts/xcodeproj_generator.rb"

  /// The identity of each in-family ACP package.
  static let acpIdentities: Set = ["foundationmodelsacp", "foundationmodelsacpclient"]

  /// Tells whether the demo project was generated in this checkout.
  static var demoProjectIsGenerated: Bool {
    guard let url = try? PackageFiles.file(demoPath) else { return false }
    return FileManager.default.fileExists(atPath: url.path(percentEncoded: false))
  }

  /// Reads the in-family ACP pins of one `Package.resolved` file, in identity
  /// order.
  ///
  /// - Parameter path: The path of the file, relative to the package root.
  /// - Returns: The pins of the ACP packages.
  private func acpPins(of path: String) throws -> [ResolvedFile.Pin] {
    let data = try Data(contentsOf: PackageFiles.file(path))
    return try JSONDecoder().decode(ResolvedFile.self, from: data).pins
      .filter { Self.acpIdentities.contains($0.identity) }
      .sorted { $0.identity < $1.identity }
  }

  @Test(.enabled(if: demoProjectIsGenerated, "The demo project is generated by Scripts/test-examples.sh."))
  func theGeneratedDemoProjectPinsTheRootACPRevisions() throws {
    let root = try acpPins(of: Self.rootPath)

    #expect(try acpPins(of: Self.demoPath) == root)
  }

  @Test func theGeneratorCopiesTheRootPinsIntoTheDemoProject() throws {
    let generator = try PackageFiles.text(of: Self.generatorPath)
    let projectRelativePath = try #require(
      Self.demoPath.firstMatch(of: /\.xcodeproj\/(?<inner>.+)$/)?.output.inner)

    #expect(generator.contains("PROJECT_PINS_PATH = '\(projectRelativePath)'"))
    #expect(generator.contains("File.join(PACKAGE_RELATIVE_PATH, 'Package.resolved')"))
    #expect(generator.contains("FileUtils.cp(pins, destination)"))
  }
}
